// This file is automatically generated. Do not edit it directly.
// Re-export do cliente melhorado de services/supabase
export { supabase } from '@/services/supabase/client';
export type { Database } from './types';